### ISSUE TITLE
Entering non-integer amount in "account orders: received" number field sometimes interpreted as zero

### ISSUE THREAD

**Issue by mjavurek** [foodcoops/foodsoft#830] opened 2021-02-17 17:14 UTC
Sometimes (not always) we observed in our foodsoft instance, if we enter a non-integer amount in the "received" field of an order group, like e.g. 0.9, the number is interpreted as 0 and as a consequence, the order group is removed from this article. Unfortunately I could not reproduce the bug in the demo installation https://app.foodcoops.net/demo/finance/balancing/new?order_id=101
![foodsoft-order-account-non-integer](https://user-images.githubusercontent.com/57668028/108241190-db42b500-714b-11eb-9bfe-db9eca464008.PNG)

**Comment by wvengen** [comment] 2021-03-03 12:20
Ouch, that doesn't sound too good.
If anyone sees this too, or can reproduce it, please report!

**Comment by mjavurek** [comment] 2021-03-03 12:43
Some colleagues from my foodcoop and I could reproduce it several times in our foodsoft instance, but we stopped doing it since we were in danger of loosing some of our order data. I tried it in the demo installation but could nor reproduce it there. So maybe I should make a test order in our foodsoft instance, but what can I do if I observe the error again?

**Comment by paroga** [comment] 2021-03-03 12:47
the problem is that [the database accepts only integers](https://github.com/foodcoops/foodsoft/blob/dee12418882353a863a5cc03a764cf3bd6e367d1/db/schema.rb#L306). We need to change the database schema first.

**Comment by twothreenine** [comment] 2021-03-04 22:12
Could it be that you use decimal comma in your foodsoft instance @mjavurek ?
We have the same issue in our instance with decimal comma (which is automatically used in some languages like German)
The field works fine with decimal numbers as long as they are entered with decimal point. Confusingly, if the field already contains a decimal number, it is shown with decimal comma in German (as all decimal numbers) and if you then want to adjust it, you have to remember to replace the comma with a point, otherwise it is interpreted as zero and the ordergroup is removed.



> 
> 
> the problem is that [the database accepts only integers](https://github.com/foodcoops/foodsoft/blob/dee12418882353a863a5cc03a764cf3bd6e367d1/db/schema.rb#L306). We need to change the database schema first.

I don't know why but it works fine for me as long as I use decimal point.

**Comment by twothreenine** [comment] 2021-03-04 23:34
Same issue occurs in the "manage orders" menu, when you sort by articles or groups.
![manage-orders-decimal-comma](https://user-images.githubusercontent.com/22921479/110044732-ea2f8700-7d49-11eb-922a-35de479c873b.png)

I guess this should be fixed in the [group order articles helper](https://github.com/foodcoops/foodsoft/blob/dee12418882353a863a5cc03a764cf3bd6e367d1/app/helpers/group_order_articles_helper.rb) or the [delta input](https://github.com/foodcoops/foodsoft/blob/dee12418882353a863a5cc03a764cf3bd6e367d1/app/inputs/delta_input.rb) itself

**Comment by mjavurek** [comment] 2021-03-24 13:16
I hope that the issue is resolved with https://github.com/foodcoops/foodsoft/pull/853

**Comment by twothreenine** [comment] 2021-03-24 14:01
> I hope that the issue is resolved with #853

No. I just tried out the [branch](https://github.com/paroga/foodsoft/tree/urd) and could replicate this issue there nonetheless.
I don't even see how those issues should be connected. The fields changed in #853 are in the `order_article` table and therefore refer to the amount received/billed for the foodcoop, not for a single order group.
Have you (also @paroga) read my two earlier comments where I pointed this out?

**Comment by mjavurek** [comment] 2021-03-25 07:48
> Could it be that you use decimal comma in your foodsoft instance @mjavurek ?

Yes that's true, it's exactly the way you describe it.

**Comment by lentschi** [comment] 2021-04-23 14:20
@twothreenine 

> No. I just tried out the branch and could replicate this issue there nonetheless.
> I don't even see how those issues should be connected.

You're right, @paroga seems to have fixed another issue with his PR, that is only loosely connected to this one:
When using the _Receive_ page one could not enter comma values at all. This affects the balancing page only in the way, that if the supplier delivered only a fraction of the unit, it is most likely that order groups must also be billed only in fractions (which then leads to the bug you actually described).

So in short: @paroga's fix here is just for the sake of DB consistency.

The actual problem you're describing should be fixed by https://github.com/foodcoops/foodsoft/pull/868:
The rails code _sometimes_ (Note: not on the receive page - should probably be added there too?) encodes the value displayed by the UI using [number_with_precision](https://apidock.com/rails/ActionView/Helpers/NumberHelper/number_with_precision). This will produce locale-aware comma separators (e.g. `1,2` on a German client).
However the `delta_input` javascript logic always converted any invalid value to 0 and since it isn't locale-aware, colons **are considered invalid**. Then again a value of 0 means the respective order group didn't pick up anything, so it was removed from the list (This last part is _not_ a bug IMO).

**My fix would do the following:**

1. Convert any entered colon to a comma internally.
2. Don't immediately post the ajax form, if the value is _still_ invalid. (E.g. if the user enters a non-numeric/negative/... value) The field is then just displayed with a red border signifying that it hasn't been posted. (Maybe we still should improve UX here...?)

**Closed** 2022-12-14 09:07 UTC
Labels: bug
