### ISSUE TITLE
Tolerance faulty?

### ISSUE THREAD

**Issue by Tamriel** [foodcoops/foodsoft#376] opened 2015-07-29 23:29 UTC
If there is a 5kg bundle and Alice buys 2kg + 1kg tolerance, Bob is only able to buy 2kg, not 3kg (he then would take Alice's 1 kg tolerance).

Wouldn't it be nice if Bob could buy 3kg, since Alice only wants 2kg?

**Comment by wvengen** [comment] 2015-07-30 17:34
Definitely! I'm surprised that Bob can't buy 3kg. Could you show how this happens (screenshots would help)?

**Comment by Tamriel** [comment] 2015-07-31 00:01
Left half is Alice, right half is Bob.

Bob thinks 'Oh, 2kg yet to buy'
![1](https://cloud.githubusercontent.com/assets/5037153/8997949/b1792790-3727-11e5-81f8-30e1fa82a35b.png)

Bob buys 2kg
![2](https://cloud.githubusercontent.com/assets/5037153/8997951/b39a4586-3727-11e5-9ce2-5dc0c088636f.png)

Bob buys 3kg, but opens another bundle instead of getting Alice's 1kg tolerance
![3](https://cloud.githubusercontent.com/assets/5037153/8997954/b5dde32a-3727-11e5-9854-ddd07590ac29.png)

**Comment by wvengen** [comment] 2015-07-31 10:19
Thanks, indeed I would "Fehlend" to remain zero, and Bob's toleranz not to be used.
I'm curious to know if this would happen before #365. What version (or commit) of Foodsoft are you using?

**Comment by Tamriel** [comment] 2015-07-31 12:44
I use v4.4.1

**Comment by wvengen** [comment] 2015-09-05 12:49
@akirk would you have a clue here?

**Comment by akirk** [comment] 2015-09-05 15:14
@wvengen I can't reproduce this on master. Actually it seems the behavior @Tamriel observes was fixed by my patch ([test script for the screenshots below](https://gist.github.com/akirk/00c3055b89dba1347bea)):


### before #365:
#### step 1:
<img width="330" alt="f5a7c4c9-1" src="https://cloud.githubusercontent.com/assets/203408/9699850/cd6cb1f2-53f0-11e5-9b9f-cffb83ee42ec.png">
#### step 2:
<img width="330" alt="f5a7c4c9-2" src="https://cloud.githubusercontent.com/assets/203408/9699853/d18b52d4-53f0-11e5-8b05-5a6bbd352a03.png">
#### step 3:
<img width="358" alt="f5a7c4c9-3" src="https://cloud.githubusercontent.com/assets/203408/9699855/d4dab4ac-53f0-11e5-8809-c15f91dbd280.png">
#### step 4:
<img width="322" alt="f5a7c4c9-4" src="https://cloud.githubusercontent.com/assets/203408/9699876/05d0fbac-53f1-11e5-95b3-7b6b5626c998.png">
### master:
#### step 1:
<img width="316" alt="master-1" src="https://cloud.githubusercontent.com/assets/203408/9699877/05f7f0ae-53f1-11e5-8c4c-d6de4e445771.png">
#### step 2:
<img width="313" alt="master-2" src="https://cloud.githubusercontent.com/assets/203408/9699879/05f891d0-53f1-11e5-9708-9c302f74192d.png">
#### step 3:
<img width="312" alt="master-3" src="https://cloud.githubusercontent.com/assets/203408/9699880/05fad346-53f1-11e5-87d3-93975deb641e.png">
#### step 4:
<img width="343" alt="master-4" src="https://cloud.githubusercontent.com/assets/203408/9699878/05f82b64-53f1-11e5-97a4-7ae818fc7168.png">

**Comment by akirk** [comment] 2015-09-05 15:20
Btw, in @Tamriel's screenshot you can see that Bob actually does get the 3 items he wants (if he weren't it would say 2+1), it's just the missing that displays something wrong, which was fixed by my patch.

**Comment by akirk** [comment] 2015-09-05 15:26
@wvengen could it be that you mixed something up for the 4.4.1 release? It doesn't seem to contain my patch.

**Comment by wvengen** [comment] 2015-09-07 07:24
@akirk thank you for testing this! And you're right, 4.4.1 does not contain your changes (I mixed up my memory), it [contains](https://github.com/foodcoops/foodsoft/blob/master/CHANGELOG.md#foodsoft-441) only a fix for an install issue.
I'll look into this a bit more later.

**Comment by wvengen** [comment] 2015-09-14 16:58
I guess it's time for a new release then, I'll starting preparing it.

**Comment by wvengen** [comment] 2015-09-14 16:59
And thanks again @akirk for confirming that this works on master.

**Closed** 2015-09-14 16:59 UTC
